#!/usr/bin/env Rscript

# Aim: wrapper to perform inference
# Copyright (C) 2015-2016 INRA
# License: AGPL-3+
# Persons: Timothee Flutre [cre,aut]
# Versioning: https://github.com/timflutre/model4all

prog.name <- "model4all_infer"
prog.version <- "0.1.0" # http://semver.org/

R.v.maj <- as.numeric(R.version$major)
R.v.min.1 <- as.numeric(strsplit(R.version$minor, "\\.")[[1]][1])
if(R.v.maj < 2 || (R.v.maj == 2 && R.v.min.1 < 15))
    stop("require R >= 2.15 (for paste0)", call.=FALSE)

##' Display the help on stdout
##'
##' The format complies with help2man (http://www.gnu.org/s/help2man) but use --no-discard-stderr
##' @title Help
help <- function(){
  txt <- paste0("`", prog.name, "' is a wrapper to perform inference.\n")
  txt <- paste0(txt, "\n")
  txt <- paste0(txt, "Usage: ", prog.name, " [OPTIONS] ...\n")
  txt <- paste0(txt, "\n")
  txt <- paste0(txt, "Options:\n")
  txt <- paste0(txt, "  -h, --help\tdisplay the help and exit\n")
  txt <- paste0(txt, "  -V, --version\toutput version information and exit\n")
  txt <- paste0(txt, "  -v, --verbose\tverbosity level (0/default=1/2/3)\n")
  txt <- paste0(txt, "      --theme\tname of the theme (e.g. 'quantgen')\n")
  txt <- paste0(txt, "      --src\tpath to the directory containing '<theme>_infer.R'\n")
  txt <- paste0(txt, "\t\tcurrent by default\n")
  txt <- paste0(txt, "\t\tthis file should contain at least these functions:\n")
  txt <- paste0(txt, "\t\t- <theme>InferMain\n")
  txt <- paste0(txt, "\t\t- <theme>InferHelp\n")
  txt <- paste0(txt, "\t\t- <theme>InferVersion\n")
  txt <- paste0(txt, "\t\tfunctions below are optional but strongly advised:\n")
  txt <- paste0(txt, "\t\t- <theme>InferParseArgs\n")
  txt <- paste0(txt, "\t\t- <theme>InferCheckOptions\n")
  txt <- paste0(txt, "      --themhlp\texecute '<theme>InferHelp'\n")
  txt <- paste0(txt, "      --themver\texecute '<theme>InferVersion'\n")
  txt <- paste0(txt, "      --args\targuments for '<theme>InferMain'\n")
  txt <- paste0(txt, "\t\tas a string, e.g. \"--pkg INLA\"\n")
  txt <- paste0(txt, "      --task\tname of the task (default='test')\n")
  txt <- paste0(txt, "\t\twill be used as a prefix for input and output files\n")
  txt <- paste0(txt, "      --simd\tpath to the 'simulation' directory\n")
  txt <- paste0(txt, "\t\tfrom which files will be loaded; current by default\n")
  txt <- paste0(txt, "      --infd\tpath to the 'inference' directory\n")
  txt <- paste0(txt, "\t\tto which files will be saved; current by default\n")
  txt <- paste0(txt, "      --sid\tidentifier of the simulation to use (e.g. '1' for the first)\n")
  txt <- paste0(txt, "\t\totherwise use all of them\n")
  txt <- paste0(txt, "      --nchains\tnumber of chains, when needed (default=1)\n")
  txt <- paste0(txt, "      --niters\tnumber of iterations, when needed (default=1000)\n")
  txt <- paste0(txt, "      --burnin\tnumber of iterations to discard as burn-in, when needed (default=100)\n")
  txt <- paste0(txt, "      --thin\tthining, when needed (default=5)\n")
  txt <- paste0(txt, "      --ncores\tnumber of cores to use (default=1)\n")
  txt <- paste0(txt, "\t\tso that all simulated datasets can be analyzed in parallel\n")
  txt <- paste0(txt, "\n")
  txt <- paste0(txt, "Examples:\n")
  txt <- paste0(txt, "  ", prog.name, " --theme quantgen --themhlp\n")
  txt <- paste0(txt, "\n")
  txt <- paste0(txt, "Report bugs to <timothee.flutre@supagro.inra.fr>.")
  write(txt, stdout())
}

##' Display version and license information on stdout
##'
##' The person roles comply with R's guidelines (The R Journal Vol. 4/1, June 2012). To comply with help2man (http://www.gnu.org/s/help2man), use --no-discard-stderr.
##' @title Version
version <- function(){
  txt <- paste0(prog.name, " ", prog.version, "\n")
  txt <- paste0(txt, "\n")
  txt <- paste0(txt, "Copyright (C) 2015-2016 INRA.\n")
  txt <- paste0(txt, "License AGPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/agpl.html>\n")
  txt <- paste0(txt, "\n")
  txt <- paste0(txt, "Written by Timothee Flutre [cre,aut].")
  write(txt, stdout())
}

##' Parse the program arguments
##'
##' Allow short and long options
##' @param prog.args character vector
##' @param prog.opts named list of program options with default values
##' @return named list
##' @author Timothee Flutre
parseArgs <- function(prog.args, prog.opts){
  i <- 0
  while(i < length(prog.args)){ # use "while" loop for options with no argument
    i <- i + 1
    if(prog.args[i] == "-h" || prog.args[i] == "--help"){
      help()
      quit("no", status=0)
    }
    else if(prog.args[i] == "-V" || prog.args[i] == "--version"){
      version()
      quit("no", status=0)
    }
    else if(prog.args[i] == "-v" || prog.args[i] == "--verbose"){
      prog.opts$verbose <- as.numeric(prog.args[i+1])
      i <- i + 1
    }
    else if(prog.args[i] == "--theme"){
      prog.opts$theme <- prog.args[i+1]
      i <- i + 1
    }
    else if(prog.args[i] == "--src"){
      prog.opts$src.dir <- prog.args[i+1]
      i <- i + 1
    }
    else if(prog.args[i] == "--themhlp"){
      prog.opts$theme.help <- TRUE
    }
    else if(prog.args[i] == "--themver"){
      prog.opts$theme.version <- TRUE
    }
    else if(prog.args[i] == "--args"){
      prog.opts$theme.args <- strsplit(x=prog.args[i+1],
                                       split=" ")[[1]]
      i <- i + 1
    }
    else if(prog.args[i] == "--task"){
      prog.opts$task <- prog.args[i+1]
      i <- i + 1
    }
    else if(prog.args[i] == "--simd"){
      prog.opts$simul.dir <- prog.args[i+1]
      i <- i + 1
    }
    else if(prog.args[i] == "--infd"){
      prog.opts$infer.dir <- prog.args[i+1]
      i <- i + 1
    }
    else if(prog.args[i] == "--sid"){
      prog.opts$sid <- as.numeric(prog.args[i+1])
      i <- i + 1
    }
    else if(prog.args[i] == "--nchains"){
      prog.opts$nb.chains <- as.numeric(prog.args[i+1])
      i <- i + 1
    }
    else if(prog.args[i] == "--niters"){
      prog.opts$nb.iters <- as.numeric(prog.args[i+1])
      i <- i + 1
    }
    else if(prog.args[i] == "--burnin"){
      prog.opts$burnin <- as.numeric(prog.args[i+1])
      i <- i + 1
    }
    else if(prog.args[i] == "--thin"){
      prog.opts$thin <- as.numeric(prog.args[i+1])
      i <- i + 1
    }
    else if(prog.args[i] == "--ncores"){
      prog.opts$nb.cores <- as.numeric(prog.args[i+1])
      i <- i + 1
    }
    else{
      write(paste0(prog.name, ": invalid option -- ", prog.args[i], "\n"), stderr())
      help()
      quit("no", status=1)
    }
  }

  return(prog.opts)
}

##' Check program options
##'
##' @param prog.opts named list
##' @return nothing
##' @author Timothee Flutre
checkOptions <- function(prog.opts){
  if(is.null(prog.opts$theme)){
    write("ERROR: missing compulsory option --theme\n", stderr())
    help()
    quit("no", status=1)
  }
  if(is.null(prog.opts$src.dir)){
    write("ERROR: missing compulsory option --src\n", stderr())
    help()
    quit("no", status=1)
  }
  if(! dir.exists(prog.opts$src.dir)){
    write(paste0("ERROR: can't find directory ", prog.opts$src.dir, "\n"), stderr())
    help()
    quit("no", status=1)
  }
  prog.opts$theme.file <- paste0(prog.opts$src.dir, "/",
                                 prog.opts$theme, "_infer.R")
  if(! file.exists(prog.opts$theme.file)){
    write(paste0("ERROR: can't find file ", prog.opts$theme.file, "\n"), stderr())
    help()
    quit("no", status=1)
  }
  source(prog.opts$theme.file)
  themeInferMain <- get(x=paste0(prog.opts$theme, "InferMain"))
  themeInferHelp <- get(x=paste0(prog.opts$theme, "InferHelp"))
  themeInferVersion <- get(x=paste0(prog.opts$theme, "InferVersion"))
  if(prog.opts$theme.help){
    themeInferHelp()
    quit("no", status=0)
  }
  if(prog.opts$theme.version){
    themeInferVersion()
    quit("no", status=0)
  }
  if(is.null(prog.opts$task)){
    write("ERROR: missing compulsory option --task\n", stderr())
    help()
    quit("no", status=1)
  }
  if(! dir.exists(prog.opts$simul.dir)){
    write(paste0("ERROR: can't find directory ", prog.opts$simul.dir, "\n"),
          stderr())
    help()
    quit("no", status=1)
  }
  if(! dir.exists(prog.opts$infer.dir)){
    dir.create(prog.opts$infer.dir)
  }
  if(any(is.na(prog.opts$nb.iters), is.na(prog.opts$burnin),
         is.na(prog.opts$thin))){
    write(paste0("ERROR: --niters, --burnin and --thin shouldn't be NA \n"),
          stderr())
    help()
    quit("no", status=1)
  }

  suppressPackageStartupMessages(library(parallel))
  suppressPackageStartupMessages(library(methods)) # for "as"
}

##' List 'simulation' files
##'
##'
##' @param prog.opts named list
##' @return vector of characters
##' @author Timothee Flutre
listSimulFiles <- function(prog.opts){
  lFiles <- Sys.glob(paste0(prog.opts$simul.dir, "/",
                            prog.opts$task, "_simul_*.RData"))

  if(length(lFiles) == 0){
    msg <- paste0("ERROR: can't find any file '", prog.opts$task,
                  "_simul_*.RData' in '", prog.opts$simul.dir, "'")
    write(msg, stderr())
    quit("no", status=1)
  }

  if(! is.null(prog.opts$sid)){
    if(prog.opts$sid > length(lFiles)){
      write(paste0("ERROR: can't use simulation #", prog.opts$sid,
                   " as there are only ", length(lFiles), " files"),
            stderr())
      quit("no", status=1)
    }
    lFiles <- lFiles[prog.opts$sid]
  }

  if(prog.opts$verbose > 0)
    write(paste0("nb of 'simul' files: ", length(lFiles)), stdout())

  return(lFiles)
}

##' Perform the inference(s)
##'
##'
##' @param prog.opts list
##' @return nothing
##' @author Timothee Flutre
run <- function(prog.opts){
  lSimFiles <- listSimulFiles(prog.opts)
  nb.sims <- length(lSimFiles)

  themeInferMain <- get(x=paste0(prog.opts$theme, "InferMain"))
  tmp <-
    mclapply(1:nb.sims,
             function(sid){
               if(prog.opts$verbose > 0)
                 write(paste0(sid, "/", nb.sims), stdout())
               infer.file <- sprintf(
                   paste0(prog.opts$sim.dir, "/", prog.opts$task, "_infer_%0",
                          floor(log10(nb.sims))+1, "i.RData"),
                   sid)
               themeInferMain(prog.args=prog.opts$theme.args,
                              simul.file=lSimFiles[sid],
                              infer.dir=prog.opts$infer.dir,
                              infer.file=infer.file,
                              nb.chains=prog.opts$nb.chains,
                              nb.iters=prog.opts$nb.iters,
                              burnin=prog.opts$burnin,
                              thin=prog.opts$thin)
             },
             mc.cores=prog.opts$nb.cores,
             mc.silent=ifelse(prog.opts$nb.cores > 1, TRUE, FALSE))
}

##' Entry point of the program
##'
##'
##' @return nothing
##' @author Timothee Flutre
main <- function(prog.args){
  prog.opts <- list(verbose=1,
                    theme=NULL,
                    src.dir=getwd(),
                    theme.file=NULL,
                    theme.help=FALSE,
                    theme.version=FALSE,
                    theme.args=NULL,
                    task="test",
                    simul.dir=getwd(),
                    infer.dir=getwd(),
                    sid=NULL,
                    nb.chains=1,
                    nb.iters=10^3,
                    burnin=10^2,
                    thin=5,
                    nb.cores=1)

  prog.opts <- parseArgs(prog.args, prog.opts)

  checkOptions(prog.opts)

  if(prog.opts$verbose > 0){
    start.time <- format(Sys.time(), "%Y-%m-%d %H:%M:%S")
    write(paste0("START ", prog.name, " ", prog.version, " ", start.time),
          stdout())
    prog.args <- commandArgs(trailingOnly=TRUE)
    write(paste("cmd-line:", prog.name, paste(prog.args, collapse=" ")), stdout())
    write(paste0("cwd: ", getwd()), stdout())
  }

  pt <- system.time(run(prog.opts))
  if(prog.opts$verbose > 0)
     print(pt)

  if(prog.opts$verbose > 0){
    end.time <- format(Sys.time(), "%Y-%m-%d %H:%M:%S")
    difft <- as.numeric(
        difftime(as.POSIXct(end.time, format="%Y-%m-%d %H:%M:%S"),
                 as.POSIXct(start.time, format="%Y-%m-%d %H:%M:%S"),
                 units="days"))
    ## difft <- 1 + 2/24 + 3/(24*60) + 3/(24*3600) # 1d 2h 3m 4s in days
    difft.d <- floor(difft)
    difft.h <- floor(((difft - difft.d) * 24) %% 24)
    difft.m <- floor(((difft - difft.d - difft.h/24) * 24*60) %% (24 * 60))
    difft.s <- floor(((difft - difft.d - difft.h/24 - difft.m/(24*60)) *
                      24*60*60) %% (24 * 60 * 60))
    run.length <- sprintf("%02i:%02i:%02i", difft.h, difft.m, difft.s)
    write(paste0("END ", prog.name, " ", prog.version, " ", end.time,
                 " (", run.length, ")"), stdout())
    ## print(object.size(x=lapply(ls(), get)), units="Kb") # return an error I don't understand
  }
}

if(! interactive()){
  cmdArgs <- commandArgs(trailingOnly=TRUE)
  main(cmdArgs)
}
